adding eksctl check

diff --git a/makefiles/Makefile b/makefiles/Makefile
--- a/makefiles/Makefile
+++ b/makefiles/Makefile
@@ -38,6 +38,7 @@ create-cluster:
 		kind get clusters | grep ${KIND_CLUSTER} || kind create cluster --config ${BINDIR}/kind-cluster-with-extramounts.yaml --name ${KIND_CLUSTER}
 	elif [ ${INFRASTRUCTURE} = "eks" ]; then\
 		echo "Creating eks cluster ..."
+		check-eksctl
 		eksctl create cluster --name ${CLUSTER_NAME} \
 			--region ${AWS_REGION} \
 			--version ${EKS_K8S_VERSION} \
@@ -61,6 +62,7 @@ delete-cluster:
 		kind delete cluster --name ${KIND_CLUSTER}
 	elif [ ${INFRASTRUCTURE} = "eks" ]; then\
 		echo "Deleting eks cluster ..."
+		check-eksctl
 		eksctl delete cluster --region ${AWS_REGION} --name ${CLUSTER_NAME} --wait || \
 		aws cloudformation delete-stack --region ${AWS_REGION} --stack-name eksctl-${CLUSTER_NAME}-cluster
 	elif [ ${INFRASTRUCTURE} = "mvm" ]; then\
@@ -73,3 +75,10 @@ delete-cluster:
 		echo "Deleting gke cluster ..."
 		gcloud container clusters delete ${GKE_CLUSTER_NAME} --region ${GCP_REGION} --project ${GCP_PROJECT_NAME} -q
 	fi
+
+check-eksctl:
+	@which eksctl  >/dev/null 2>&1 || (echo "eksctl binary not found, installing ..." && \
+	curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_${OS}_amd64.tar.gz" | tar xz -C /tmp && \
+	chmod +x /tmp/eksctl && \
+	sudo mv /tmp/eksctl /usr/local/bin && \
+	eksctl version)
